In [34]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
#vamos inserir o valor de webdriver do navegador web Chrome na variável nav
nav = webdriver.Chrome()
# pesquisar cotação do dólar
nav.get("https://www.google.com/")
# vamos colocar o código HTML que indica o elemento da caixa de pesquisa para o programa buscar no navegador (caminho xpath)
nav.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("Cotação do Dólar")
nav.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)                                                                           
cotacao_dolar = nav.find_element_by_xpath('/html/body/div[7]/div/div[9]/div[1]/div/div[2]/div[2]/div/div/div[1]/div/div/div/div/div[1]/div/div[1]/div[1]/div[2]/span[1]').get_attribute('data-value')
print(cotacao_dolar)

# cotação euro
nav = webdriver.Chrome()
nav.get("https://www.google.com/")
nav.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("Cotação do Euro")
nav.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)                                                                           
cotacao_euro = nav.find_element_by_xpath('/html/body/div[7]/div/div[9]/div[1]/div/div[2]/div[2]/div/div/div[1]/div/div/div/div/div[1]/div/div[1]/div[1]/div[2]/span[1]').get_attribute('data-value')
print(cotacao_euro)

# cotação do ouro
nav.get("https://www.melhorcambio.com/") # acessar site
aba_original = nav.window_handles[0] #armazena que a aba original é a 0
nav.find_element_by_xpath('/html/body/div[15]/div[2]/div/table[2]/tbody/tr[2]/td[2]/a/img').click() # pega caminho full xpath do ícone da cotação do ouro e pede para clicar nele
# para trocar de aba, vamos informar de onde viemos e para onde vamos
aba_nova = nav.window_handles[1]
nav.switch_to.window(aba_nova)
cotacao_ouro = nav.find_element_by_id('comercial').get_attribute('value')
cotacao_ouro = cotacao_ouro.replace(",", ".")
print(cotacao_ouro)

nav.quit()

#importar pandas para importar planilha

import pandas as pd
produtos_df = pd.read_excel(r"C:\Users\conta\Documents\Educação\2021 - Desenvolvimento de Software\Curso Hashtag Programação - Python, dados, automação\Aula 3 - Automação com integração web - Web-scraping\Produtos.xlsx")
display(produtos_df)
# modificar o dataframe produtos
# método .loc seleciona apenas as linhas com "Dólar na coluna Moeda
# ao encontrar linhas escrito "Dólar", o .loc altera o valor na coluna "Cotação"
produtos_df.loc[produtos_df['Moeda']=="Dólar", "Cotação"]=float(cotacao_dolar)
produtos_df.loc[produtos_df['Moeda']=="Euro", "Cotação"]=float(cotacao_euro)
produtos_df.loc[produtos_df['Moeda']=="Ouro", "Cotação"]=float(cotacao_ouro)
display(produtos_df)

#alterar valor de preço base e preço final

produtos_df['Preço Base Reais'] = produtos_df['Cotação'] * produtos_df["Preço Base Original"]
produtos_df['Preço Final'] = produtos_df['Preço Base Reais'] * produtos_df['Margem']
display(produtos_df)

# exportar nova planilha sem a coluna com o índice de linhas (, index=False)
produtos_df.to_excel(r"C:\Users\conta\Documents\Educação\2021 - Desenvolvimento de Software\Curso Hashtag Programação - Python, dados, automação\Aula 3 - Automação com integração web - Web-scraping\Produtos Atualizado.xlsx", index=False)

<ipython-input-34-2308231ab1f5>:8: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  nav.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("Cotação do Dólar")
<ipython-input-34-2308231ab1f5>:9: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  nav.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)
<ipython-input-34-2308231ab1f5>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  cotacao_dolar = nav.find_element_by_xpath('/html/body/div[7]/div/div[9]/div[1]/div/div[2]/div[2]/div/div/div[1]/div/div/div/div/div[1]/div/div[1]/div[1]/div[2]/span[1]').get_attribute('data-value')

5.4841

<ipython-input-34-2308231ab1f5>:16: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  nav.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("Cotação do Euro")
<ipython-input-34-2308231ab1f5>:17: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  nav.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)
<ipython-input-34-2308231ab1f5>:18: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  cotacao_euro = nav.find_element_by_xpath('/html/body/div[7]/div/div[9]/div[1]/div/div[2]/div[2]/div/div/div[1]/div/div/div/div/div[1]/div/div[1]/div[1]/div[2]/span[1]').get_attribute('data-value')

6.3563186840000006

<ipython-input-34-2308231ab1f5>:24: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  nav.find_element_by_xpath('/html/body/div[15]/div[2]/div/table[2]/tbody/tr[2]/td[2]/a/img').click() # pega caminho full xpath do ícone da cotação do ouro e pede para clicar nele
<ipython-input-34-2308231ab1f5>:28: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  cotacao_ouro = nav.find_element_by_id('comercial').get_attribute('value')

322.97

,Produtos,Preço Base Original,Moeda,Cotação,Preço Base Reais,Margem,Preço Final
0,Câmera Canon,999.99,Dólar,5,4999.95,1.40,6999.930
1,Carro Renault,4500.00,Euro,6,27000.00,2.00,54000.000
2,Notebook Dell,899.99,Dólar,5,4499.95,1.70,7649.915
3,IPhone,799.00,Dólar,5,3995.00,1.70,6791.500
4,Carro Fiat,3000.00,Euro,6,18000.00,1.90,34200.000
5,Celular Xiaomi,480.48,Dólar,5,2402.40,2.00,4804.800
6,Joia 20g,20.00,Ouro,350,7000.00,1.15,8050.000

,Produtos,Preço Base Original,Moeda,Cotação,Preço Base Reais,Margem,Preço Final
0,Câmera Canon,999.99,Dólar,5.484100,4999.95,1.40,6999.930
1,Carro Renault,4500.00,Euro,6.356319,27000.00,2.00,54000.000
2,Notebook Dell,899.99,Dólar,5.484100,4499.95,1.70,7649.915
3,IPhone,799.00,Dólar,5.484100,3995.00,1.70,6791.500
4,Carro Fiat,3000.00,Euro,6.356319,18000.00,1.90,34200.000
5,Celular Xiaomi,480.48,Dólar,5.484100,2402.40,2.00,4804.800
6,Joia 20g,20.00,Ouro,322.970000,7000.00,1.15,8050.000

,Produtos,Preço Base Original,Moeda,Cotação,Preço Base Reais,Margem,Preço Final
0,Câmera Canon,999.99,Dólar,5.484100,5484.045159,1.40,7677.663223
1,Carro Renault,4500.00,Euro,6.356319,28603.434078,2.00,57206.868156
2,Notebook Dell,899.99,Dólar,5.484100,4935.635159,1.70,8390.579770
3,IPhone,799.00,Dólar,5.484100,4381.795900,1.70,7449.053030
4,Carro Fiat,3000.00,Euro,6.356319,19068.956052,1.90,36231.016499
5,Celular Xiaomi,480.48,Dólar,5.484100,2635.000368,2.00,5270.000736
6,Joia 20g,20.00,Ouro,322.970000,6459.400000,1.15,7428.310000